/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminOrganizationsOrganizationIdRouteRouteImport } from './routes/admin/organizations/$organizationId/route'
import { Route as AdminOrganizationsOrganizationIdIndexRouteImport } from './routes/admin/organizations/$organizationId/index'
import { Route as AdminOrganizationsOrganizationIdTodosRouteImport } from './routes/admin/organizations/$organizationId/todos'
import { Route as AdminOrganizationsOrganizationIdSettingsRouteImport } from './routes/admin/organizations/$organizationId/settings'
import { Route as AdminOrganizationsOrganizationIdMembersRouteImport } from './routes/admin/organizations/$organizationId/members'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsOrganizationIdRouteRoute =
  AdminOrganizationsOrganizationIdRouteRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationsOrganizationIdIndexRoute =
  AdminOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrganizationsOrganizationIdRouteRoute,
  } as any)
const AdminOrganizationsOrganizationIdTodosRoute =
  AdminOrganizationsOrganizationIdTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => AdminOrganizationsOrganizationIdRouteRoute,
  } as any)
const AdminOrganizationsOrganizationIdSettingsRoute =
  AdminOrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminOrganizationsOrganizationIdRouteRoute,
  } as any)
const AdminOrganizationsOrganizationIdMembersRoute =
  AdminOrganizationsOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminOrganizationsOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdRouteRouteWithChildren
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/organizations/$organizationId/members': typeof AdminOrganizationsOrganizationIdMembersRoute
  '/admin/organizations/$organizationId/settings': typeof AdminOrganizationsOrganizationIdSettingsRoute
  '/admin/organizations/$organizationId/todos': typeof AdminOrganizationsOrganizationIdTodosRoute
  '/admin/organizations/$organizationId/': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/organizations/$organizationId/members': typeof AdminOrganizationsOrganizationIdMembersRoute
  '/admin/organizations/$organizationId/settings': typeof AdminOrganizationsOrganizationIdSettingsRoute
  '/admin/organizations/$organizationId/todos': typeof AdminOrganizationsOrganizationIdTodosRoute
  '/admin/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdRouteRouteWithChildren
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/organizations/$organizationId/members': typeof AdminOrganizationsOrganizationIdMembersRoute
  '/admin/organizations/$organizationId/settings': typeof AdminOrganizationsOrganizationIdSettingsRoute
  '/admin/organizations/$organizationId/todos': typeof AdminOrganizationsOrganizationIdTodosRoute
  '/admin/organizations/$organizationId/': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/success'
    | '/todos'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/organizations/$organizationId'
    | '/admin/organizations/'
    | '/admin/organizations/$organizationId/members'
    | '/admin/organizations/$organizationId/settings'
    | '/admin/organizations/$organizationId/todos'
    | '/admin/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/success'
    | '/todos'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/organizations'
    | '/admin/organizations/$organizationId/members'
    | '/admin/organizations/$organizationId/settings'
    | '/admin/organizations/$organizationId/todos'
    | '/admin/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/success'
    | '/todos'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/organizations/$organizationId'
    | '/admin/organizations/'
    | '/admin/organizations/$organizationId/members'
    | '/admin/organizations/$organizationId/settings'
    | '/admin/organizations/$organizationId/todos'
    | '/admin/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
  SuccessRoute: typeof SuccessRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/$organizationId': {
      id: '/admin/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/admin/organizations/$organizationId'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/$organizationId/': {
      id: '/admin/organizations/$organizationId/'
      path: '/'
      fullPath: '/admin/organizations/$organizationId/'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AdminOrganizationsOrganizationIdRouteRoute
    }
    '/admin/organizations/$organizationId/todos': {
      id: '/admin/organizations/$organizationId/todos'
      path: '/todos'
      fullPath: '/admin/organizations/$organizationId/todos'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdTodosRouteImport
      parentRoute: typeof AdminOrganizationsOrganizationIdRouteRoute
    }
    '/admin/organizations/$organizationId/settings': {
      id: '/admin/organizations/$organizationId/settings'
      path: '/settings'
      fullPath: '/admin/organizations/$organizationId/settings'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof AdminOrganizationsOrganizationIdRouteRoute
    }
    '/admin/organizations/$organizationId/members': {
      id: '/admin/organizations/$organizationId/members'
      path: '/members'
      fullPath: '/admin/organizations/$organizationId/members'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdMembersRouteImport
      parentRoute: typeof AdminOrganizationsOrganizationIdRouteRoute
    }
  }
}

interface AdminOrganizationsOrganizationIdRouteRouteChildren {
  AdminOrganizationsOrganizationIdMembersRoute: typeof AdminOrganizationsOrganizationIdMembersRoute
  AdminOrganizationsOrganizationIdSettingsRoute: typeof AdminOrganizationsOrganizationIdSettingsRoute
  AdminOrganizationsOrganizationIdTodosRoute: typeof AdminOrganizationsOrganizationIdTodosRoute
  AdminOrganizationsOrganizationIdIndexRoute: typeof AdminOrganizationsOrganizationIdIndexRoute
}

const AdminOrganizationsOrganizationIdRouteRouteChildren: AdminOrganizationsOrganizationIdRouteRouteChildren =
  {
    AdminOrganizationsOrganizationIdMembersRoute:
      AdminOrganizationsOrganizationIdMembersRoute,
    AdminOrganizationsOrganizationIdSettingsRoute:
      AdminOrganizationsOrganizationIdSettingsRoute,
    AdminOrganizationsOrganizationIdTodosRoute:
      AdminOrganizationsOrganizationIdTodosRoute,
    AdminOrganizationsOrganizationIdIndexRoute:
      AdminOrganizationsOrganizationIdIndexRoute,
  }

const AdminOrganizationsOrganizationIdRouteRouteWithChildren =
  AdminOrganizationsOrganizationIdRouteRoute._addFileChildren(
    AdminOrganizationsOrganizationIdRouteRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationsOrganizationIdRouteRoute: typeof AdminOrganizationsOrganizationIdRouteRouteWithChildren
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationsOrganizationIdRouteRoute:
    AdminOrganizationsOrganizationIdRouteRouteWithChildren,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
  SuccessRoute: SuccessRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
