name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

on:
  push:
    branches:
      - main

  pull_request:

  merge_group:

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: lts/krypton

      - name: Install bun
        uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install

      - name: Check for dirty git repo
        run: |
          git update-index -q --refresh
          test -z "$(git status --porcelain --untracked-files=all)"

      - name: Lint
        run: bun run lint

      - name: Check Types
        run: bun run check-types
