[package]
name = "escrow"
version = "0.1.0"
edition = "2021"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
]

[lib]
crate-type = ["cdylib"]

[features]
alloc = []
client = []
debug = []
idl-build = ["quasar-lang/idl-build"]

[dependencies]
quasar-lang = { git = "https://github.com/blueshift-gg/quasar", rev = "81958ae82eaf7fb512d17cf40fec19873534e8f3" }
quasar-spl = { git = "https://github.com/blueshift-gg/quasar", rev = "81958ae82eaf7fb512d17cf40fec19873534e8f3" }
solana-instruction = { version = "3.2.0" }
